### PR TITLE
Create CohenEdenPlantSteal.yml

### PR DESCRIPTION
**Pull request by ilanrcohen**

### CODE REVIEW

**Review by Mountlex — APPROVED** [review]
thanks!

**Comment by ilanrcohen** [comment]
Hi,

Could you please check why the publication "Plant and Steal" is not
appearing on the website?
The file name is: `papers/CohenEdenPlantSteal.yml`.

Thanks in advance,
Ilan

**Comment by Mountlex** [comment]
Hi @ilanrcohen 

your paper is visible on the website, but it is further down in the list. Generally, papers are ordered by arxiv publication date, but I feel there is something broken. I'll look into that after the holidays, as I am planning to rewriting parts of the website.
Anyways, thanks for pointing this out!

Best
Alex

**Comment by ilanrcohen** [comment]
Found it,  thank you very much for your response and for the excellent work
you do on this website!

Best wishes,
Ilan

**Pull request merged**
